export const APPROVEITEM_REQUEST = "APPROVEITEM_REQUEST";
export const APPROVEITEM_LOADING = "APPROVEITEM_PENDING";
export const APPROVEITEM_ERROR = "APPROVEITEM_ERROR";
export const APPROVEITEM_SUCCESS = "APPROVEITEM_SUCCESS";
export const DISAPPROVEITEM_REQUEST = "DISAPPROVEITEM_REQUEST";
export const DISAPPROVEITEM_LOADING = "DISAPPROVEITEM_PENDING";
export const DISAPPROVEITEM_ERROR = "DISAPPROVEITEM_ERROR";
export const DISAPPROVEITEM_SUCCESS = "DISAPPROVEITEM_SUCCESS";
