export const BIDFORITEM_REQUEST = 'BIDFORITEM_REQUEST'
export const BIDFORITEM_LOADING = 'BIDFORITEM_PENDING'
export const BIDFORITEM_ERROR = 'BIDFORITEM_ERROR'
export const BIDFORITEM_SUCCESS = 'BIDFORITEM_SUCCESS'