export const SIMILARITEMS_FETCH = "SIMILARITEMS_FETCH";
export const SIMILARITEMS_PENDING = "SIMILARITEMS_PENDING";
export const SIMILARITEMS_ERROR = "SIMILARITEMS_ERROR";
export const SIMILARITEMS_SUCCESS = "SIMILARITEMS_SUCCESS";
export const MOSTPOPULARITEMS_FETCH = "MOSTPOPULARITEMS_FETCH";
export const MOSTPOPULARITEMS_PENDING = "MOSTPOPULARITEMS_PENDING";
export const MOSTPOPULARITEMS_ERROR = "MOSTPOPULARITEMS_ERROR";
export const MOSTPOPULARITEMS_SUCCESS = "MOSTPOPULARITEMS_SUCCESS";
