export const ITEMS_FETCH = "ITEMS_FETCH";
export const ITEMS_PENDING = "ITEMS_PENDING";
export const ITEMS_ERROR = "ITEMS_ERROR";
export const ITEMS_SUCCESS = "ITEMS_SUCCESS";
export const EXPIRED_FETCH = "EXPIRED_FETCH";
export const EXPIRED_PENDING = "EXPIRED_PENDING";
export const EXPIRED_ERROR = "EXPIRED_ERROR";
export const EXPIRED_SUCCESS = "EXPIRED_SUCCESS";
