export const LASTITEMS_FETCH = "LASTITEMS_FETCH";
export const LASTITEMS_PENDING = "LASTITEMS_PENDING";
export const LASTITEMS_ERROR = "LASTITEMS_ERROR";
export const LASTITEMS_SUCCESS = "LASTITEMS_SUCCESS";
