export const ONBIDDEDITEMS_FETCH = "ONBIDDEDITEMS_FETCH";
export const ONBIDDEDITEMS_PENDING = "ONBIDDEDITEMS_PENDING";
export const ONBIDDEDITEMS_ERROR = "ONBIDDEDITEMS_ERROR";
export const ONBIDDEDITEMS_SUCCESS = "ONBIDDEDITEMS_SUCCESS";
