export const UPDATEITEM_REQUEST = "UPDATEITEM_REQUEST";
export const UPDATEITEM_LOADING = "UPDATEITEM_LOADING";
export const UPDATEITEM_ERROR = "UPDATEITEM_ERROR";
export const UPDATEITEM_SUCCESS = "UPDATEITEM_SUCCESS";
